In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Movie_regression.csv', header=0)

In [3]:
df.head()

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection
0,20.1264,59.62,0.462,36524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,YES,109.60,223.840,Thriller,23,494,48000
1,20.5462,69.14,0.531,35668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,NO,146.64,243.456,Drama,42,462,43200
2,20.5458,69.14,0.531,39912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,NO,147.88,2022.400,Comedy,38,458,69400
3,20.6474,59.36,0.542,38873.890,119.3,6.895,7.035,6.920,7.020,8.26,516279,YES,185.36,225.344,Drama,45,472,66800
4,21.3810,59.36,0.542,39701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,NO,176.48,225.792,Drama,55,395,72400

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64
 11  3D_available         506 non-null    object
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object
 15  Avg_age_actors       506 non-null    int64
 16  Num_multiplex        506 non-null    int64
 17  Collection           506 non-null    int64
dtypes: float64(12), int64(4), object(2)
memory usage: 71.3+ KB

## Missing Value Imputation

In [5]:
df['Time_taken'].mean()

np.float64(157.3914979757085)

In [6]:
df['Time_taken'].fillna(df['Time_taken'].mean(), inplace=True)

/var/folders/r8/f70r5rz147b1mdb71m265bdw0000gn/T/ipykernel_8636/3102984186.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Time_taken'].fillna(df['Time_taken'].mean(), inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64
 11  3D_available         506 non-null    object
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object
 15  Avg_age_actors       506 non-null    int64
 16  Num_multiplex        506 non-null    int64
 17  Collection           506 non-null    int64
dtypes: float64(12), int64(4), object(2)
memory usage: 71.3+ KB

## Dummy variables Creation

In [8]:
df = pd.get_dummies(df, columns=['3D_available', 'Genre'], drop_first=True)

In [9]:
df.head()

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,3D_available_YES,Genre_Comedy,Genre_Drama,Genre_Thriller
0,20.1264,59.62,0.462,36524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,109.60,223.840,23,494,48000,True,False,False,True
1,20.5462,69.14,0.531,35668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,146.64,243.456,42,462,43200,False,False,True,False
2,20.5458,69.14,0.531,39912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,147.88,2022.400,38,458,69400,False,True,False,False
3,20.6474,59.36,0.542,38873.890,119.3,6.895,7.035,6.920,7.020,8.26,516279,185.36,225.344,45,472,66800,True,False,True,False
4,21.3810,59.36,0.542,39701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,176.48,225.792,55,395,72400,False,False,True,False

## X-y split

In [10]:
X = df.loc[:, df.columns != 'Collection']
y = df['Collection']
type(X), type(y)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

## Test Train Split

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Standardize the data

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler().fit(X_train)

In [15]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [16]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]], shape=(102, 19))

## Training Regression Tree

In [17]:
from sklearn.svm import SVR

In [18]:
svr = SVR(kernel='linear', C = 1000)

In [19]:
svr.fit(X_train_std, y_train)

SVR(C=1000, kernel='linear')

### Predicting values using trained model

In [20]:
y_test_pred = svr.predict(X_test_std)
y_train_pred = svr.predict(X_train_std)

In [21]:
y_test_pred

array([54170.53503625, 42284.13073448, 47467.48411681, 18129.17355969,
       48399.2694108 , 39866.86998058, 34007.32532044, 43289.77824001,
       30366.10675075, 47064.86893308, 12791.33749785, 38408.82653373,
       37559.85784034,  8779.61135966, 66820.90169749, 61934.22332501,
       38795.59236698, 65521.75338819, 57150.63894057, 43345.30648075,
       53845.74438999, 39163.9161095 , 41674.15698489, 58329.2948265 ,
       42884.07327353, 13145.18400653, 40922.72188255, 29718.76094568,
       74630.97971381, 44573.11287424, 36854.7122831 , 37424.55686816,
       37582.94829537, 40845.85075693, 52096.6358182 , 35540.25290306,
       25313.83859774, 36522.56259703, 36623.75409555, 35831.61173002,
       47370.51557929, 45957.66677543, 44656.54171505, 27680.22280557,
       50609.67508545, 46713.98056409, 33197.61112633, 40047.74770769,
       15830.8986982 , 51791.84658664, 41241.55116877, 39132.63366916,
       47511.3684718 , 67543.6845176 , 25372.80865713, 41659.98849411,
       41183.13416828, 34329.69827939, 21291.90329438, 39332.20090511,
       41482.76666808, 41305.705476  , 65283.01275883, 64854.422162  ,
       28470.27249381, 63678.89600398, 37109.92800204, 39308.41079599,
       42108.77491375, 47272.96039093, 46402.38045685, 48948.09910041,
       56494.74395678, 59884.05633069, 49074.24411709, 10885.11690224,
       73708.55119772, 44774.58652223, 59273.21131031, 38000.03908567,
       50616.25130199, 43141.53644229, 32228.32910879, 81337.35382161,
       79338.4819698 , 47926.47727737, 50711.45023189, 30108.91100051,
       49496.94125933, 38011.42325353, 34085.66885372, 34287.73114639,
       43273.16443822, 59282.17937564, 43881.88478087, 42304.07003505,
       -4537.98340671, 52502.3163472 , 36710.19229576, 32246.91091579,
       49741.80875784, 48435.89960542])

### Model Performance

In [22]:
from sklearn.metrics import r2_score, mean_squared_error

In [23]:
mean_squared_error(y_test, y_test_pred)

160153135.39404392

In [24]:
r2_score(y_test, y_test_pred)

0.5025135728682723

In [25]:
r2_score(y_train, y_train_pred)

0.7124450931551838